SELECT PRODUCT_CODE, PRICE * SALES_AMOUNT AS SALES
FROM PRODUCT AS P
JOIN (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID
    ) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;