SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(DAILY_FEE * 30 * DISCOUNT_RATE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN (
    SELECT 
        CAR_TYPE, 
        DURATION_TYPE, 
        1 - DISCOUNT_RATE * 0.01 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%'
) AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE 
    (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
    AND 500000 <= DAILY_FEE * 30 * DISCOUNT_RATE
    AND DAILY_FEE * 30 * DISCOUNT_RATE < 2000000
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE GREATEST(start_date, DATE('2022-11-01')) < LEAST(end_date, DATE('2022-11-30'))
)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;