SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE * AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT, PRODUCE_DATE
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;